# === PostgreSQL (???????? ??????) ? ???????????????? ===
# db.url=jdbc:postgresql://3e24e-rw.db.pub.dbaas.postgrespro.ru:5432/dbstud
# db.user=lebedev_aa1
# db.password=R$Fo#2SC%iQX
# db.driver=org.postgresql.Driver

# === MySQL (????????? ??????) ? ??????? ===
db.url=jdbc:mysql://localhost:3306/cyber_club_db
db.user=root
db.password=Root123!
db.driver=com.mysql.cj.jdbc.Driver